version: '3'

services:
  web:
    build: .
    command: gunicorn trading_dashboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - redis
      - celery

  nginx:
    image: nginx:latest
    ports:
      - "8888:8888"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web

  celery:
    build: .
    command: celery -A trading_dashboard worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  celery-beat:
    build: .
    command: celery -A trading_dashboard beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis