# Generated by Django 5.0.3 on 2024-03-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email_verified',
        ),
    ]
